// reactjs-sem-project/src/Profile.js
import React, {useEffect, useState} from "react";
import {useNavigate} from "react-router";
import AuthService from "./services/AuthService";

export default function Profile() {
    const navigate = useNavigate();

    const [user, setUser] = useState(undefined);

    useEffect(() => {
        AuthService.getCurrentUserInfo().then((u) => {
            setUser(u);
        }).catch(() => navigate('/'));
    }, []);

    return (
        <>
            {user && (
                <div className="row d-flex justify-content-center bg-white">
                    <div className="col-5 pb-5 mt-2 bg-dark bg-opacity-10">
                        <h1 className={'mt-4 text-center text-uppercase'}>Údaje</h1>
                        <p><span className={'fw-bold'}>Jméno: </span>{user.firstName}</p>
                        <p><span className={'fw-bold'}>Příjmení: </span>{user.lastName}</p>
                        <p><span className={'fw-bold'}>Datum narození: </span>{user.dateOfBirth}</p>
                        <p><span className={'fw-bold'}>Výška: </span>{user.height}</p>
                    </div>
                </div>)}
        </>
    )
}

// angular-sem-project/src/app/components/profile/profile.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-profile',
  templateUrl: './profile.component.html',
  styleUrls: ['./profile.component.scss']
})
export class ProfileComponent implements OnInit {

  user = {
    firstName: 'Filip',
    lastName: 'Svoboda',
    dateOfBirth: '02.11.1999',
    height: '174',
    weight: '80',
    BMI: '26.8',
    BMR: '1700',
  }

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="row d-flex justify-content-center bg-white">
  <div class="col-5 pb-5 mt-2 bg-dark bg-opacity-10">
    <h2 class="mt-4 text-center text-uppercase">Údaje</h2>
    <p><span class="fw-bold">Jméno: </span>{{user.firstName}}</p>
    <p><span class="fw-bold">Příjmení: </span>{{user.lastName}}</p>
    <p><span class="fw-bold">Datum narození: </span>{{user.dateOfBirth}}</p>
    <p><span class="fw-bold">Výška: </span>{{user.height}}</p>
    <p><span class="fw-bold">Váha: </span>{{user.weight}}</p>
    <p><span class="fw-bold">BMI: </span>{{user.BMI}}</p>
    <p><span class="fw-bold">BMR: </span>{{user.BMR}}</p>

  </div>
</div>
