// angular-sem-project/src/app/components/navbar/navbar.component.ts
import {Component, OnInit} from '@angular/core';
import {MatDialog} from "@angular/material/dialog";
import {AuthDialogComponent} from "../auth-dialog/auth-dialog.component";

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.scss']
})
export class NavbarComponent implements OnInit {
  user: boolean = false;
  loginButtonText: string = '';
  name: string = 'Filip';

  constructor(
    private dialog: MatDialog,
  ) {
    this.loginButtonText = this.user ? 'Odhlásit' : 'Přihlásit';
  }

  ngOnInit(): void {

  }

  login(): void {
    // this.user = !this.user;
    // this.loginButtonText = this.user ? 'Odhlásit' : 'Přihlásit';
    this.dialog.open(AuthDialogComponent, {
      width: '420px'
    })
  }

}

<div class="row w-100 bg-primary g-0">
  <div class="col-8 d-flex justify-content-start p-2">
    <a class="mx-2 text-decoration-none d-flex align-items-center text-black" routerLink="/"><img src="assets/logo.png" class="enlarge" width="28"></a>
    <button mat-button routerLink="/about">O aplikaci</button>
    <button mat-button routerLink="/calculator">Kalkulačka</button>
    <button mat-button routerLink="/diary">Deník</button>
  </div>
  <div class="col-4 d-flex justify-content-end p-2">
    <button mat-flat-button [ngClass]="{'me-2': user}" (click)="login()" [color]="user ? 'warn' : null">{{loginButtonText}}</button>
    <button mat-flat-button routerLink="/profile" *ngIf="user">{{ name }}</button>
  </div>
</div>

// reactjs-sem-project/src/components/Navbar.js
import React, {useState} from "react";
import {Link} from "react-router-dom";
import {Button, Dialog, DialogContent, DialogTitle, TextField} from "@mui/material";

export default function Navbar(props) {
    const user = props.user;

    return (
        <div className={"row w-100 g-0 my-bg-color"}>
            <div className={"col-8 d-flex justify-content-start p-2"}>
                <Link className={"mx-2 text-decoration-none d-flex align-items-center text-black"} to={'/'}>
                    <img src="logo.png" className="enlarge" width="28" alt={'logo'}/>
                </Link>
                <Button component={Link} to={'/calculator'} className={'text-black'}>Kalkulačka</Button>
                {user ? <Button component={Link} to={'/diary'} className={'text-black'}>Deník</Button> : null}
            </div>
            {user ? <LoggedIn user={user}/> : <NotLoggedIn/>}
        </div>
    )
};

const LoggedIn = (props) => {

    return (
        <div className={"col-4 d-flex justify-content-end p-2"}>
            <Button color={"error"} variant={'contained'} className={"me-2"}
                    onClick={() => console.log("klik - odhlásit")}>Odhlásit</Button>
            <Button variant={'contained'} color={'inherit'} component={Link}
                    to={'/profile'}>{props.user.username}</Button>
        </div>
    );
};

const NotLoggedIn = () => {
    const [dialogOpen, setDialogOpen] = useState(false);
    
    const handleLoginClick = () => {
        setDialogOpen(true);
    }

    const handleDialogClose = () => {
        setDialogOpen(false);
    }

    return (
        <div className={"col-4 d-flex justify-content-end p-2"}>
            <Button variant={'contained'} color={'inherit'} onClick={handleLoginClick}>Přihlásit</Button>
            <Dialog open={dialogOpen} onBackdropClick={handleDialogClose}>
                <DialogTitle>Přihlášení</DialogTitle>
                <DialogContent>
                    <TextField label={'Uživatelské jméno'} className={'mt-2'}/>
                    <br/>
                    <TextField label={'Heslo'} className={'my-3'}/>
                    <br/>
                    <Button variant={'contained'}>Přihlásit</Button>
                </DialogContent>
            </Dialog>
        </div>

    );
};
