// reactjs-sem-project/src/Calculator.js
import React, {useEffect, useState} from "react";
import {
    Tabs,
    Tab,
    TextField,
    Button,
    Radio,
    RadioGroup,
    FormControl,
    FormControlLabel,
    Snackbar, Alert, TableContainer, Paper, Table, TableHead, TableCell, TableRow, TableBody
} from "@mui/material";
import MyLocalStorageService from "./services/MyLocalStorageService";
import CalculatorService from "./services/CalculatorService";

const localStorage = new MyLocalStorageService();


export default function Calculator() {

    const [showTab, setShowTab] = useState(false);
    const [value, setValue] = useState(0);
    const [entries, setEntries] = useState([]);

    const handleTabs = (e, val) => {
        setValue(val);
    };

    useEffect(() => {
        setEntries(localStorage.loadCalculatorEntries);
    }, [])

    useEffect(() => {
        if (entries.length > 0){
            localStorage.saveCalculatorEntries(entries);
            setShowTab(true);
        } else {
            setShowTab(false);
            setValue(0);
        }
    }, [entries]);

    return (
        <div className="row d-flex w-100 justify-content-center mt-3">
            <div className="col-8 text-center">
                <Tabs value={value} onChange={handleTabs}>
                    <Tab label={'Kalkulačka'}/>
                    {showTab ? <Tab label={'Výsledky'}/> : null}
                </Tabs>
                <CalculatorTab value={value} index={0}>
                    <CalculatorForm setShowTab={setShowTab} setValue={setValue} entries={entries} setEntries={setEntries}/>
                </CalculatorTab>
                <CalculatorTab value={value} index={1}>
                    <CalculatorEntries entries={entries} setEntries={setEntries}/>
                </CalculatorTab>
            </div>
        </div>
    )
}


const CalculatorTab = (props) => {
    const {children, value, index} = props;
    return (
        <>
            {value === index && children}
        </>
    )
}

const CalculatorForm = (props) => {
    const [snackbarOpen, setSnackbarOpen] = useState(false);
    const [sex, setSex] = useState('male');



    const handleSex = (event) => {
        setSex(event.target.value);
    };

    const handleSubmit = (event) => {
        const data = [];
        event.preventDefault();
        const formData = new FormData(event.target);
        formData.forEach((e) => {
            data.push(e);
        });
        if (!validateData(data)) {
            setSnackbarOpen(true);
            setTimeout(() => setSnackbarOpen(false),3000);
            return;
        }

        const today = new Date().toISOString().split('T')[0];
        const bmi = CalculatorService.calculateBMI(Number(data[3]),Number(data[2]));
        const bmr = CalculatorService.calculateBMR(Number(data[3]),Number(data[2]),Number(data[0]),data[0]);
        const entry = {date: today, age: data[0], sex: data[1], height: data[2], weight: data[3], BMI: bmi, BMR: bmr};

        const newEntries = [entry, ...props.entries];
        if (newEntries.length === 6) {
            newEntries.pop();
        }
        props.setEntries(newEntries);

        props.setShowTab(true);
        props.setValue(1);
    }

    const validateData = (data) =>  {
        const dataAge = data[0];
        const dataHeight = data[2];
        const dataWeight = data[3];
        console.log(Number(dataAge) > 120)
        if (dataAge === "" || dataHeight === "" || dataWeight === "") {
            return false;
        }
        if (isNaN(dataAge) || isNaN(dataHeight) || isNaN(dataWeight)) {
            return false;
        }
        if (Number(dataAge) < 5 || Number(dataAge) > 120) {
            return false;
        }
        if (Number(dataHeight) < 100 || Number(dataHeight) > 300) {
            return false;
        }
        if (Number(dataWeight) < 1 || Number(dataWeight) > 600) {
            return false;
        }
        return true;
    }

    return (
        <>
            <form onSubmit={handleSubmit}>
                <TextField inputProps={{inputMode:'numeric', pattern: '[0-9]{1,3}'}} label={'Věk'} name={'age'} className={'my-2'}/>
                <br/>
                <FormControl>
                    <RadioGroup defaultValue={'male'} value={sex} onChange={handleSex} name={'sex'} row>
                        <FormControlLabel control={<Radio/>} label={'Muž'} value={'male'}/>
                        <FormControlLabel control={<Radio/>} label={'Žena'} value={'female'}/>
                    </RadioGroup>
                </FormControl>
                <br/>
                <TextField inputProps={{inputMode: 'numeric', pattern: '[0-9]*'}} label={'Výška'} name={'height'} className={'mt-2'}/>
                <br/>
                <TextField inputProps={{inputMode: 'decimal'}} label={'Hmotnost'} name={'weight'} className={'my-2 mt-3'}/>
                <br/>
                <Button type={'submit'} variant={'contained'} className={'mt-2'}>Vypočítej</Button>


            </form>
            <Snackbar open={snackbarOpen}
                      autoHideDuration={3000}
                      anchorOrigin={{vertical: 'top', horizontal: 'center'}}>
                <Alert style={{backgroundColor: 'red'}} severity={'error'}>Zadejte prosím validní data</Alert>
            </Snackbar>

        </>
    )
}

const CalculatorEntries = (props) => {

    const handleClick = () => {
        localStorage.deleteCalculatorEntries();
        props.setEntries([]);
    }

    return (
        <>
            <h1>HAHA</h1>
            <TableContainer component={Paper}>
                <Table>
                    <TableHead>
                        <TableRow>
                            <TableCell>Datum</TableCell>
                            <TableCell>Věk</TableCell>
                            <TableCell>Pohlaví</TableCell>
                            <TableCell>Výška</TableCell>
                            <TableCell>Hmotnost</TableCell>
                            <TableCell>BMI</TableCell>
                            <TableCell>BMR</TableCell>
                        </TableRow>
                    </TableHead>
                    <TableBody>
                        {props.entries.map((row) => (
                            <TableRow>
                                <TableCell>{row.date}</TableCell>
                                <TableCell>{row.age}</TableCell>
                                <TableCell>{row.sex === 'male' ? 'Muž' : 'Žena'}</TableCell>
                                <TableCell>{row.height}</TableCell>
                                <TableCell>{row.weight}</TableCell>
                                <TableCell>{row.BMI}</TableCell>
                                <TableCell>{row.BMR}</TableCell>
                            </TableRow>
                        ))}
                    </TableBody>
                </Table>
            </TableContainer>
            <Button onClick={handleClick} color={'error'} variant={'contained'} className={'mt-2'}>SMAZAT</Button>
        </>
    )
}

// angular-sem-project/src/app/components/calculator/calculator.component.ts
import { Component, OnInit } from '@angular/core';
import {CalculatorService} from "../../services/calculator.service";
import {FormBuilder, FormControl} from "@angular/forms";
import {CalculatorEntry} from "../../models/calculator-entry.model";
import {MatTableDataSource} from "@angular/material/table";
import {MyLocalStorageService} from "../../services/my-local-storage.service";
import {Sex} from "../../enums/sex.enum";
import {MatSnackBar} from "@angular/material/snack-bar";


@Component({
  selector: 'app-calculator',
  templateUrl: './calculator.component.html',
  styleUrls: ['./calculator.component.scss']
})
export class CalculatorComponent implements OnInit {
  type: number = 0;
  keyExists: boolean = false;
  entries: CalculatorEntry[] = [];
  entriesDataSource: any;
  displayedColumns: string[] = ['date', 'age', 'sex', 'height', 'weight', 'BMI', 'BMR']

  result = this.formBuilder.group({
    age: new FormControl(undefined),
    sex: new FormControl(Sex.Male),
    height: new FormControl(undefined),
    weight: new FormControl(undefined)
  });

  constructor(
    private readonly calculatorService: CalculatorService,
    private readonly myLocalStorageService: MyLocalStorageService,
    private readonly formBuilder: FormBuilder,
    private readonly snackbar: MatSnackBar,
  ) { }

  ngOnInit(): void {
    console.log("ONINIT", this.entries);
    this.entries = this.myLocalStorageService.loadCalculatorEntries();
    console.log("ONINIT-přiřazení", this.entries);
    this.keyExists = this.myLocalStorageService.calculatorEntriesExist();
    this.entriesDataSource = new MatTableDataSource(this.entries);
  }

  calculate(): string {
    this.entriesDataSource = new MatTableDataSource(this.entries);
    const date = new Date().toISOString().split('T')[0];

    const calculatorEntry: CalculatorEntry = {
      date: date,
      age: this.result.controls['age'].value,
      sex: this.result.controls['sex'].value,
      height: this.result.controls['height'].value,
      weight: this.result.controls['weight'].value,
    };

    calculatorEntry.BMI = this.calculatorService.calculateBMI(calculatorEntry.weight, calculatorEntry.height);
    calculatorEntry.BMR = this.calculatorService.calculateBMR(calculatorEntry.weight,calculatorEntry.height,calculatorEntry.age,calculatorEntry.sex);
    if(this.entriesDataSource.data.length == 5) {
      this.entriesDataSource.data.pop();
    }
    this.entriesDataSource.data.unshift(calculatorEntry);
    this.myLocalStorageService.saveCalculatorEntries(this.entries);
    this.keyExists = true;
    console.log(this.entries);
    this.type = 1;
    return this.entriesDataSource.filter = "";
  }

  deleteEntries(): void {
    this.myLocalStorageService.deleteCalculatorEntries();
    this.keyExists = false;
    this.entriesDataSource = null;
    this.entries = [];
    this.snackbar.open('Data smazána', undefined, {
      duration: 3000
    })
  }
}

<div class="row d-flex w-100 justify-content-center mt-3">
  <div class="col-8 text-center">
    <mat-tab-group animationDuration="150ms" [(selectedIndex)]="type">
      <mat-tab label="Kalkulačka" (click)="type = 0">
        <form [formGroup]=result (ngSubmit)="calculate()">
          <mat-form-field>
            <mat-label>Věk</mat-label>
            <input matInput formControlName="age" type="number" min="5" max="120">
          </mat-form-field>
          <br>
          <mat-radio-group formControlName="sex">
            <mat-radio-button value="Male" [checked]="true">Muž</mat-radio-button>
            <mat-radio-button value="Female" style="margin-left: 10px;">Žena</mat-radio-button>
          </mat-radio-group>
          <br>
          <mat-form-field>
            <mat-label>Výška</mat-label>
            <input matInput formControlName="height" type="number" min="100" max="300">
          </mat-form-field>
          <br>
          <mat-form-field>
            <mat-label>Hmotnost</mat-label>
            <input matInput formControlName="weight" type="number" min="1" max="500">
          </mat-form-field>
          <br>
          <button mat-flat-button color="accent" type="submit">Vypočítat</button>
        </form>
      </mat-tab>
      <mat-tab label="Výsledky" *ngIf="keyExists">
        <table mat-table class="w-100" [dataSource]="entriesDataSource">
          <ng-container matColumnDef="date">
            <th mat-header-cell *matHeaderCellDef> Datum</th>
            <td mat-cell *matCellDef="let element"> {{element.date}}</td>
          </ng-container>
          <ng-container matColumnDef="age">
            <th mat-header-cell *matHeaderCellDef> Věk</th>
            <td mat-cell *matCellDef="let element"> {{element.age}} </td>
          </ng-container>
          <ng-container matColumnDef="sex">
            <th mat-header-cell *matHeaderCellDef> Pohlaví</th>
            <td mat-cell *matCellDef="let element"> {{element.sex}} </td>
          </ng-container>
          <ng-container matColumnDef="height">
            <th mat-header-cell *matHeaderCellDef> Výška</th>
            <td mat-cell *matCellDef="let element"> {{element.height}} </td>
          </ng-container>
          <ng-container matColumnDef="weight">
            <th mat-header-cell *matHeaderCellDef> Hmotnost</th>
            <td mat-cell *matCellDef="let element"> {{element.weight}} </td>
          </ng-container>
          <ng-container matColumnDef="BMI">
            <th mat-header-cell *matHeaderCellDef> BMI</th>
            <td mat-cell *matCellDef="let element"> {{element.BMI}} </td>
          </ng-container>
          <ng-container matColumnDef="BMR">
            <th mat-header-cell *matHeaderCellDef> BMR</th>
            <td mat-cell *matCellDef="let element"> {{element.BMR}} </td>
          </ng-container>

          <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
          <tr mat-row *matRowDef="let row; columns: displayedColumns;" class="text-start"></tr>
        </table>
        <button mat-flat-button color="warn" class="mt-2" (click)="deleteEntries()">Smazat záznamy</button>
      </mat-tab>
    </mat-tab-group>
  </div>
</div>
